# Generated by Django 4.0.5 on 2022-06-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theFeed', '0002_post_title_tag_alter_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
