# Generated by Django 4.0.5 on 2022-06-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theFeed', '0003_remove_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
