# Generated by Django 4.0.5 on 2022-06-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theFeed', '0005_post_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='posts',
            field=models.ManyToManyField(null=True, related_name='albums', to='theFeed.post'),
        ),
    ]
