# Generated by Django 4.0.5 on 2022-06-17 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theFeed', '0015_post_album_alter_album_author_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='theFeed.album'),
        ),
    ]
