# Generated by Django 4.0.5 on 2022-06-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theFeed', '0018_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
    ]
