# Generated by Django 4.0.5 on 2022-06-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theFeed', '0019_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static\\img\\missing_avatar.png', null=True, upload_to='images/'),
        ),
    ]
